---
- name : install de ubuntu
  hosts: ubuntu
  remote_user: root
  tasks:
   - name: installation de quelques paquets ubuntu
     apt: name={{ item }} update-cache=yes
     with_items:
      - vim
      - htop
      - git
      - zsh 
- name : install de debian
  hosts: debian
  remote_user: root
  tasks:
   - name: installation de quelques paquets debian
     apt: name={{ item }} update-cache=yes
     with_items:
      - vim
      - htop
      - git
      - zsh 
   - name: Creation d'un utilisateur
     user: 
      name: toto 
      password: toto 
      shell: /bin/bash 
      comment: lel
   - name: inclusion httpd
     include: httpd.yml
- name : install de serveur centos
  hosts: centos
  remote_user: root
  tasks:
   - name: installation de quelques paquets
     yum: name={{ item }} update_cache=yes
     with_items:
      - vim
      - git
      - zsh 
...
