version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
     - db_data:/var/lib/mysql
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: mysql
     MYSQL_DATABASE: ghost
     MYSQL_USER: ghostuser
     MYSQL_PASSWORD: ocrpassword
  ghost:
    depends_on:
     - db
    image: ghost
    ports:
     - "80:2368"
    restart: always 
    environment: 
     NODE_ENV: production

volumes:
 db_data: {}

